name: GitHub Pages deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy public to docs
        shell: bash {0}
        run: |
          echo "Working"
